-- Schema and RLS policy for ESP32 dummy vibration FFT uploads.
-- Run this in the Supabase SQL editor.

create table if not exists public.vibration_fft_logs (
  id bigint generated by default as identity primary key,
  device_id text not null,
  sample_count integer not null check (sample_count > 0),
  sampling_frequency_hz double precision not null check (sampling_frequency_hz > 0),
  motor_rpm double precision not null check (motor_rpm > 0),
  running_frequency_hz double precision not null check (running_frequency_hz > 0),
  overall_vibration_rms_mm_s double precision not null check (overall_vibration_rms_mm_s >= 0),
  dominant_frequency_hz double precision not null,
  rms_value double precision not null,
  peak_magnitude double precision not null,
  health_state text not null default 'good',
  health_score integer not null default 100 check (health_score >= 0 and health_score <= 100),
  fault_type text not null default 'normal',
  fundamental_energy_ratio double precision not null default 0,
  second_harmonic_energy_ratio double precision not null default 0,
  high_frequency_energy_ratio double precision not null default 0,
  iso_standard text not null default 'ISO 10816',
  iso_class text not null default 'Class I',
  signal_type text not null default 'mpu6500_accel_fft',
  created_at_ms bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  payload jsonb,
  created_at timestamptz not null default now()
);

alter table public.vibration_fft_logs
  add column if not exists motor_rpm double precision,
  add column if not exists running_frequency_hz double precision,
  add column if not exists overall_vibration_rms_mm_s double precision,
  add column if not exists health_state text,
  add column if not exists health_score integer,
  add column if not exists fault_type text,
  add column if not exists fundamental_energy_ratio double precision,
  add column if not exists second_harmonic_energy_ratio double precision,
  add column if not exists high_frequency_energy_ratio double precision,
  add column if not exists iso_standard text,
  add column if not exists iso_class text;

create index if not exists vibration_fft_logs_device_id_idx
  on public.vibration_fft_logs (device_id);

create index if not exists vibration_fft_logs_created_at_idx
  on public.vibration_fft_logs (created_at desc);

alter table public.vibration_fft_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'vibration_fft_logs'
      and policyname = 'Allow insert for anon and authenticated'
  ) then
    create policy "Allow insert for anon and authenticated"
      on public.vibration_fft_logs
      for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'vibration_fft_logs'
      and policyname = 'Allow select for authenticated'
  ) then
    create policy "Allow select for authenticated"
      on public.vibration_fft_logs
      for select
      to authenticated
      using (true);
  end if;
end $$;